### ISSUE TITLE
Docker?

### ISSUE THREAD

**Issue by antagomir** [microbiome/docker#1]
Hi @MADscientist314 - this repository has been specifically created for the miaverse docker. Any updates?

Linked to [mia issue #116](https://github.com/microbiome/mia/pull/116)

**Comment by MADscientist314** [comment]
@antagomir I uploaded the docker file and annotated the README to include the pre-built docker from dockerhub for those that just want to pull and not worry about building it.   This repo should be good to go, but am happy to add anything else you think might add contribution.

**Comment by antagomir** [comment]
Thanks for the clarification. 

I had been left with impression based on the thread in above-mentioned issue that instructions and Dockerfile could have been moved in this repository (I can do that).

I did not find annotations to README in the commit [cd669cb](https://github.com/microbiome/mia/pull/116/commits/cd669cb65fff3c495e1af663b220ee6067733caa). Is there a README?

**Comment by antagomir** [comment]
Ah, I had missed the files in this repo. Many thanks, we may need to update this later but this is a good start!
